### ISSUE TITLE
Anchor augments cannot be destroyed. (Fabric, Better Minecraft modpack).

### ISSUE THREAD

**Issue by Minecraftguy595959** [Draylar/get-off-my-lawn#44]
All of the claim anchor augments cannot be destroyed. I can destroy the anchor itself, but never the augment blocks. Using a withered claim anchor, with regeneration, chaos, and heavens wings augments. It allows me to destroy them only for a moment after I place them, any longer than that and they are no longer breakable. As an added bug, it does not detect when I leave the claim area. I retain permanent creative flight until I enter another dimension, and if I log out and log back in while in any dimension, I gain flight again.

**Comment by Galus** [comment]
I am looking into this myself, I opened an Issue about the augment for flying.... 

Also, I am running Better Minecraft FABRIC 1.17.1

**Comment by Galus** [comment]
Same as !44

**Comment by SeeJayEmm** [comment]
```
[23:36:41] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "draylar.goml.entity.ClaimAnchorBlockEntity.removeChild(net.minecraft.class_2338)" because "this.parent" is null
        at draylar.goml.entity.ClaimAugmentBlockEntity.remove(ClaimAugmentBlockEntity.java:47) ~[get-off-my-lawn-1.17-1.4.0-beta.jar:?]
        at draylar.goml.block.ClaimAugmentBlock.method_9576(ClaimAugmentBlock.java:87) ~[get-off-my-lawn-1.17-1.4.0-beta.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java:247) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.redirect$cin000$sneakBreak(class_3225.java:5041) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_21717(class_3225.java:221) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:196) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1012) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by ShadowDrakken** [comment]
Same issue with the Ender Binding augment. I've tried removing and recreating the claim, but nada.

Running Sky FABRICATION 2 v0.9.2

**Comment by NameLord** [comment]
You must destroy all the augments before destroying the Anchor
Draylar must implement if the anchor is destroied it must destroy the augments too.
