### ISSUE TITLE
Permanent Flight

### ISSUE THREAD

**Issue by Galus** [Draylar/get-off-my-lawn#45]
When breaking the heaven_wings block,

```
26.09 18:39:05 [Server] Server thread/FATAL Error executing task on Server
26.09 18:39:05 [Server] INFO java.lang.NullPointerException: Cannot invoke "draylar.goml.entity.ClaimAnchorBlockEntity.removeChild(net.minecraft.class_2338)" because "this.parent" is null
26.09 18:39:05 [Server] INFO at draylar.goml.entity.ClaimAugmentBlockEntity.remove(ClaimAugmentBlockEntity.java:47) ~[get-off-my-lawn-1.17-1.4.0-beta.jar:?]
26.09 18:39:05 [Server] INFO at draylar.goml.block.ClaimAugmentBlock.method_9576(ClaimAugmentBlock.java:87) ~[get-off-my-lawn-1.17-1.4.0-beta.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_3225.method_14266(class_3225.java:247) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_3225.method_21717(class_3225.java:221) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_3225.method_14263(class_3225.java:196) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_3244.method_12066(class_3244.java:1012) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
26.09 18:39:05 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```

I was very dissapointed this cant remove flight outside of the borders, so i went to delete the recipe via kubejs:

```
onEvent('recipes', event => {
  event.remove({id: 'goml:heaven_wings'})
```

But now that i broke the block, i can still fly.

**Comment by Galus** [comment]
I am using the Better Minecraft Fabric 1.17.1 modpack.

**Comment by Galus** [comment]
Same as #44
